### ISSUE TITLE
can't parse certain torrents

### ISSUE THREAD

**Issue by nictuku** [nictuku/Taipei-Torrent#4]
EC89E35B44F623FDA9BA451AB043A0F3949CDAF7.torrent

Apparently it's because the bencode unmarshaller is broken for maps.

**Comment by uriel** [comment]
No, I think you mean it is broken for slices/lists, I think I fixed it (by replacing ancient slice-growing-code) with append(), see:  

https://github.com/uriel/Taipei-Torrent/commit/d334f3b5b4eb45e3028b60b40420e6f01c796819

**Comment by nictuku** [comment]
Awesome, thanks. Do all bencode tests pass now?

**Comment by uriel** [comment]
Go test says so, not sure if there are any other tests to run.

**Comment by nictuku** [comment]
commit d334f3b5b4eb45e3028b60b40420e6f01c796819 seems to fix it. Thanks Uriel.
